config/routes.rb
Rails.application.routes.draw do
  
	root 'static_pages#welcome'

	get 'about_us', to: 'static_pages#about_us'

	resources :pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord

	validates :name, :description, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :nav_menu

	def nav_menu
		@pages = Page.all
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	before_action :find_page, only: [:edit, :update, :show, :destroy]

	def new
		@page = Page.new
	end

	def create
		@page = Page.new(page_params)

		if @page.save
			redirect_to pages_path
		else
			render :new
		end
	end

	def index
		@pages = Page.all

	end

	def edit
	end

	def update
		@page.update(page_params)

		if @page.save
			redirect_to pages_path
		else
			render :edit
		end

	end

	def show

	end

	def destroy
		if @page.destroy
			redirect_to pages_path
		else
			redirect_to pages_path, error: "Deleting errors"
		end
	end


	private

	def page_params
		params[:page].permit(:name, :description)
	end

	def find_page
		@page = Page.find(params[:id])
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def welcome
		@title = 'Добро пожаловать!'
	end

	def about_us
		@title = 'We test amazon deployment services'
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Заголовок" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "MyFirstProject", root_path, class: "navbar-brand"  %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "About us", about_us_path  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>ТЕКСТ</h3>
            <ul class="nav nav-list">
              <li class="nav-header"><%= link_to 'Pages', pages_path %></li>
              <% @pages.each do |page| %>
                <li><%= link_to page.name, page_path(page) %></li>
              <% end %>   
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/edit.html.erb
<h1>Edit page</h1>

<%= simple_form_for(@page, html: { class: 'form-inline' }) do |form| %>
	<%= form.error_notification %>

	<%= form.input :name %>
	<%= form.input :description %>

	<%= form.button :submit %>
<% end %>

app/views/pages/index.html.erb
<h1>Pages</h1>

<table class="table">
	<thead>
		<tr>
			<th>Name</th>
		</tr>
	</thead>
	<tbody>
		<% @pages.each do |page| %>
		<tr>
			<td>
				<%= page.name %>
			</td>
			<td>
				<%= link_to 'Edit', edit_page_path(page) %>
			</td>
			<td>
				<%= link_to 'Destroy', page_path(page), method: :delete, data: { confirm: 'Are you sure?' } %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= simple_form_for(@page, html: { class: 'form-inline' }) do |form| %>
`	<%= form.error_notification %>

	<%= form.input :name %>
	<%= form.input :description %>

	<%= form.button :submit %>
<% end %>

app/views/pages/show.html.erb
<h1><%= @page.name %></h1>

<h4><%= @page.description %></h4>

app/views/static_pages/about_us.html.erb
<h4><%= @title %></h4>

app/views/static_pages/welcome.html.erb
<h4><%= @title %></h4>